import { Category, FoodItem, Restaurant, User } from '../types';

// Mock Food Items
export const mockFoodItems: FoodItem[] = [
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh tomatoes, mozzarella, and basil',
    image: 'https://images.unsplash.com/photo-1565298507278-760aac2d3d0a',
    price: 12.99,
    originalPrice: 15.99,
    rating: 4.8,
    reviews: 124,
    category: 'Pizza',
    restaurantId: 'rest1',
    restaurantName: "Mario's Pizzeria",
    ingredients: ['Tomato sauce', 'Mozzarella cheese', 'Fresh basil', 'Olive oil'],
    allergens: ['Gluten', 'Dairy'],
    isVegetarian: true,
    isVegan: false,
    isSpicy: false,
    preparationTime: 15,
    calories: 280,
  },
  {
    id: '2',
    name: 'Beef Burger Deluxe',
    description: 'Juicy beef patty with lettuce, tomato, and special sauce',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    price: 14.50,
    rating: 4.6,
    reviews: 89,
    category: 'Burgers',
    restaurantId: 'rest2',
    restaurantName: 'Burger House',
    ingredients: ['Beef patty', 'Lettuce', 'Tomato', 'Onion', 'Special sauce', 'Brioche bun'],
    allergens: ['Gluten'],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    preparationTime: 12,
    calories: 520,
  },
  {
    id: '3',
    name: 'Chicken Caesar Salad',
    description: 'Fresh romaine lettuce with grilled chicken and caesar dressing',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    price: 11.99,
    rating: 4.7,
    reviews: 56,
    category: 'Salads',
    restaurantId: 'rest3',
    restaurantName: 'Green Garden',
    ingredients: ['Romaine lettuce', 'Grilled chicken', 'Parmesan cheese', 'Croutons', 'Caesar dressing'],
    allergens: ['Dairy', 'Gluten'],
    isVegetarian: false,
    isVegan: false,
    isSpicy: false,
    preparationTime: 8,
    calories: 350,
  },
];

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Pizza',
    image: 'https://images.unsplash.com/photo-1565298507278-760aac2d3d0a',
    icon: 'pizza',
  },
  {
    id: '2',
    name: 'Burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
    icon: 'fast-food',
  },
  {
    id: '3',
    name: 'Salads',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    icon: 'leaf',
  },
  {
    id: '4',
    name: 'Desserts',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307',
    icon: 'ice-cream',
  },
];

// Mock Restaurants
export const mockRestaurants: Restaurant[] = [
  {
    id: 'rest1',
    name: "Mario's Pizzeria",
    description: 'Authentic Italian pizza made with traditional recipes',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
    rating: 4.8,
    reviews: 324,
    deliveryTime: '25-35 min',
    deliveryFee: 2.99,
    minimumOrder: 15.00,
    categories: ['Pizza', 'Italian'],
    isOpen: true,
    distance: 1.2,
    coordinates: {
      latitude: 40.7128,
      longitude: -74.0060,
    },
  },
  {
    id: 'rest2',
    name: 'Burger House',
    description: 'Premium burgers made with fresh ingredients',
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add',
    rating: 4.6,
    reviews: 256,
    deliveryTime: '20-30 min',
    deliveryFee: 2.50,
    minimumOrder: 12.00,
    categories: ['Burgers', 'American'],
    isOpen: true,
    distance: 0.8,
    coordinates: {
      latitude: 40.7589,
      longitude: -73.9851,
    },
  },
  {
    id: 'rest3',
    name: 'Green Garden',
    description: 'Fresh and healthy salads and bowls',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe',
    rating: 4.7,
    reviews: 189,
    deliveryTime: '15-25 min',
    deliveryFee: 1.99,
    minimumOrder: 10.00,
    categories: ['Salads', 'Healthy'],
    isOpen: true,
    distance: 2.1,
    coordinates: {
      latitude: 40.7505,
      longitude: -73.9934,
    },
  },
];

// Mock User
export const mockUser: User = {
  id: 'user1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  phone: '+1 (555) 123-4567',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
  address: [
    {
      id: 'addr1',
      title: 'Home',
      address: '123 Main St, New York, NY 10001',
      latitude: 40.7128,
      longitude: -74.0060,
      isDefault: true,
    },
    {
      id: 'addr2',
      title: 'Work',
      address: '456 Business Ave, New York, NY 10002',
      latitude: 40.7589,
      longitude: -73.9851,
      isDefault: false,
    },
  ],
};